Added problem docs, part 1
iver-wharf/iver-wharf.github.io pull request #27
Opened 2021-05-11 10:22 UTC by jilleJr

- Added problem list skeleton
- Added template
- Problem docs:
	- /prob/api/internal-server-error
	- /prob/api/invalid-param-uint
	- /prob/api/invalid-param-int

2021-05-11 16:28 UTC, Pikabanga requested changes

2021-05-11 16:28 UTC, Pikabanga commented on docs/prob/api/internal-server-error.md
> +This error is the umbrella error for the Wharf API backend. If something have
```suggestion
This error is the umbrella error for the Wharf API backend. If something has
```

2021-05-11 16:28 UTC, Pikabanga commented on docs/prob/api/internal-server-error.md
> +If a Go panic occurrs in one of the endpoints, then then API will quickly
```suggestion
If a Go panic occurrs in one of the endpoints, then the API will quickly
```

2021-05-11 16:28 UTC, Pikabanga commented on docs/prob/api/internal-server-error.md
> +recover, return an `/prob/api/internal-server-error` response to the client,
```suggestion
recover, return a `/prob/api/internal-server-error` response to the client,
```

2021-05-11 16:28 UTC, Pikabanga commented on docs/prob/api/invalid-param-int.md
> +but fails because of invalid value.
```suggestion
The problem is related to the backend trying to parse or validate an input value
but fails because of invalid an value.
```

2021-05-11 16:28 UTC, Pikabanga commented on docs/prob/api/invalid-param-uint.md
> +but fails because of invalid value.
```suggestion
The problem is related to the backend trying to parse or validate an input value
but fails because of an invalid value.
```

2021-05-12 09:25 UTC, jilleJr commented on docs/prob/api/invalid-param-uint.md
> +letters instead of digits.
Good note. I've added yet another paragraph about it.

2021-05-17 14:57 UTC, Pikabanga approved these changes

2021-05-18 11:09 UTC, fredx30 approved these changes

2021-05-18 12:06 UTC, merged