Add documentation for error responses
iver-wharf/iver-wharf.github.io pull request #57
Opened 2021-06-14 18:37 UTC by Alexamakans

- Added documentation for error responses
- Fixed lint warnings

2021-06-15 12:24 UTC, fredx30 approved these changes

2021-06-15 15:25 UTC, jilleJr requested changes
Rejecting until https://github.com/iver-wharf/wharf-provider-github/pull/16 has been resolved and merged

2021-06-21 11:04 UTC, Alexamakans commented
Apologies!
I meant to re-request review over at https://github.com/iver-wharf/wharf-provider-github/pull/16

2021-07-14 12:51 UTC, Alexamakans commented
Replaced by #63

2021-07-14 12:51 UTC, closed without merging