Added documentation for wharf-provider-gitlab error responses
iver-wharf/iver-wharf.github.io pull request #59
Opened 2021-06-15 10:05 UTC by Alexamakans

Closes #58

2021-06-15 12:52 UTC, Pikabanga approved these changes

2021-06-15 15:23 UTC, jilleJr requested changes
Rejecting until https://github.com/iver-wharf/wharf-provider-gitlab/pull/15 has been resolved and merged

2021-06-23 12:39 UTC, fredx30 commented
> Rejecting until [iver-wharf/wharf-provider-gitlab#15](https://github.com/iver-wharf/wharf-provider-gitlab/pull/15) has been resolved and merged

The linkage between PRs should be mentioned in the description. Personally i like the `- [] Todo Item` notation. That way this is clearly marked not ready for merge. These ticks also show through into the github pull requests overview page.

2021-07-14 12:51 UTC, closed without merging

2021-07-14 12:51 UTC, Alexamakans commented
Replaced by #63