Added documentation for wharf-provider-azuredevops error responses
iver-wharf/iver-wharf.github.io pull request #61
Opened 2021-06-15 12:47 UTC by Alexamakans

Closes #60

2021-06-15 12:59 UTC, jilleJr requested changes

2021-06-15 12:59 UTC, jilleJr commented on docs/prob/api/provider/invalid-name.md
> +- Azure DevOps provider: <https://github.com/iver-wharf/wharf-api/issues/new>
This change seems wrong.

2021-06-15 12:59 UTC, jilleJr commented on docs/prob/_sidebar.md
> +  - [/prob/provider/azuredevops/unmarshal-project-error](/prob/provider/azuredevops/unmarshal-project-error.md)
There are a lot of problems here. Maybe you could generalize some of them? Maybe it's not that important to have 4 different problem types for posting/putting project data into the Wharf API

2021-06-15 15:24 UTC, jilleJr requested changes
Rejecting until https://github.com/iver-wharf/wharf-provider-azuredevops/pull/14 has been resolved and merged

2021-07-14 12:52 UTC, Alexamakans commented
Replaced by #63

2021-07-14 12:52 UTC, closed without merging